'use client';
import React, { useState } from 'react';
import Header from '../components/Header';
import PageTitle from '../components/PageTitle';
import Footer from '../components/Footer';
import Link from 'next/link';

const TERMS = [
  { term: "Access", letter: "A", plain: "The old term for parenting time — the right of a parent to spend time with a child. Saskatchewan replaced this word with parenting time in 2020. You may still see it in older court orders.", example: "An order from 2015 might say the father shall have access every other weekend. A new order would say parenting time." },
  { term: "Adjournment", letter: "A", plain: "Postponing a court appearance to a later date. Either party can request one, but a judge must agree. Courts dislike unnecessary adjournments.", example: "Your lawyer becomes ill the week before your hearing. You apply for an adjournment and the judge reschedules it for six weeks later." },
  { term: "Admissible Evidence", letter: "A", plain: "Evidence that a court is allowed to consider when making a decision. Not all evidence is admissible — hearsay, illegally obtained evidence, and certain records may be excluded.", example: "A text message from the other parent is likely admissible. What your friend told you they overheard is probably not." },
  { term: "Affidavit", letter: "A", plain: "A written statement of facts that you swear or affirm is true in front of a Commissioner for Oaths. It is your sworn evidence to the court. You must sign it in front of the Commissioner — not before.", example: "Your affidavit might describe your current living situation, your relationship with your children, and why your proposed parenting plan is in their best interests." },
  { term: "Affidavit of Service", letter: "A", plain: "A sworn statement completed by the person who delivered your court documents to the other party, confirming that service happened, when, where, and how.", example: "After your friend hands the Notice of Application to the other parent, they fill out and swear this form to prove it was done properly." },
  { term: "Answer", letter: "A", plain: "The court form filed by the respondent to respond to the applicant's claims and make their own requests.", example: "If the other parent filed a Petition asking for sole parenting time, you would file an Answer disagreeing and asking for shared parenting time instead." },
  { term: "Applicant", letter: "A", plain: "The person who started the court case by filing the application or petition. The other person is the respondent.", example: "If you filed the Notice of Application, you are the Applicant. Your name appears first on all court documents." },
  { term: "Application", letter: "A", plain: "A formal request asking the court to make an order about parenting, support, property, or other family law matters.", example: "A Notice of Application is how you start a court case without needing a full divorce." },
  { term: "Balance of Probabilities", letter: "B", plain: "The standard of proof in family court. You must show that your version of events is more likely true than not — more than 50%. This is a lower bar than the criminal standard of beyond a reasonable doubt.", example: "You claim the other parent has a drinking problem. You need to show it is more likely true than not — not prove it beyond all doubt." },
  { term: "Best Interests of the Child", letter: "B", plain: "The most important factor courts consider when making any decision about children. It includes 16 specific factors in Saskatchewan law, such as the child's safety, emotional wellbeing, and relationship with each parent.", example: "Even if you and the other parent agree on a schedule, the judge will still check that it serves the best interests of the children." },
  { term: "Best Interests Factors", letter: "B", plain: "The specific list of 16 factors Saskatchewan courts must consider when deciding what is in a child's best interests. Includes: safety, relationship with each parent, cultural identity, the child's views depending on age, and more.", example: "One factor is the willingness of each parent to support the child's relationship with the other parent. A parent who badmouths the other parent may be seen negatively on this factor." },
  { term: "Case Conference", letter: "C", plain: "An informal meeting with a judge to discuss the issues in your case, try to narrow the disputes, and sometimes reach a partial or full agreement without going to trial.", example: "At a Case Conference, the judge might say this arrangement seems reasonable for parenting time. This is not a final order, but it guides the parties." },
  { term: "Case Management", letter: "C", plain: "A court process designed to move cases forward efficiently. A judge or court officer oversees timelines, identifies issues, and ensures both parties are following the rules.", example: "A Case Management judge might set a strict timeline: disclosure due in 30 days, JCC in 60 days, and a trial date reserved for 90 days out." },
  { term: "Chambers", letter: "C", plain: "A court session for hearing shorter applications and motions — not full trials. Most interim orders are made in Chambers. In Saskatchewan, you book a Chambers date to bring most applications.", example: "You need an interim order for parenting time while your case proceeds. You file an application and book a Chambers date to have it heard by a judge." },
  { term: "Child Protection", letter: "C", plain: "Legal proceedings initiated by the Ministry of Social Services when there are concerns a child is in need of protection. Governed by the Child and Family Services Act, not the Children's Law Act.", example: "If a social worker files a Protection Application, you are in child protection proceedings — not regular family court. Different rules, different timelines, different stakes." },
  { term: "Child Support", letter: "C", plain: "Money paid by one parent to the other to help cover the costs of raising a child. The amount is calculated using the Federal Child Support Guidelines based on the paying parent's income.", example: "If you earn $60,000/year and have 2 children in the other parent's primary care, the guidelines table says you would pay approximately $872/month." },
  { term: "Children's Law Act 2020", letter: "C", plain: "Saskatchewan's primary legislation governing custody, parenting time, and decision-making for children when parents separate. Introduced updated language and principles replacing the older Act.", example: "When a judge decides parenting arrangements in Saskatchewan, they are applying the Children's Law Act, 2020. The law lists 16 specific best interests factors." },
  { term: "Cohabitation", letter: "C", plain: "Living together as a couple. In Saskatchewan, couples who have cohabited for at least 2 years or have a child together have legal rights and obligations similar to married couples for some purposes.", example: "You lived with your partner for 3 years and have a child together. When you separate, provincial law may give you rights to spousal support." },
  { term: "Collaborative Law", letter: "C", plain: "A dispute resolution process where both parties and their lawyers agree in writing to resolve everything outside of court. If it breaks down, both lawyers must withdraw and new lawyers are hired for court.", example: "You and your ex hire collaborative lawyers, sign a participation agreement, and meet to negotiate a parenting plan and support over several sessions — without going to court." },
  { term: "Commissioner for Oaths", letter: "C", plain: "A person authorized by law to witness the signing of sworn documents like affidavits. They watch you sign, then stamp and sign the document themselves. Available at law offices, banks, and credit unions.", example: "Before filing your affidavit, you bring it unsigned to a Commissioner for Oaths at a law office. They confirm your identity, watch you sign, and then stamp it." },
  { term: "Common-Law", letter: "C", plain: "A relationship where two people live together as a couple without being legally married. In Saskatchewan, common-law partners have certain legal rights after 2 years of cohabitation or upon having a child together.", example: "You were never married but lived with your partner for 4 years and have a child. You are a common-law couple and your separation is governed by provincial law, not the Divorce Act." },
  { term: "Consent Order", letter: "C", plain: "A court order that both parties have agreed to and signed. A judge then approves it, making it legally binding. Much faster and cheaper than a contested hearing.", example: "You and the other parent agree on a parenting schedule. You both sign a draft Consent Order and submit it to the court. The judge reviews and signs it without a hearing." },
  { term: "Contact", letter: "C", plain: "Time spent with a child by someone who is not a guardian — such as grandparents or other important people in the child's life. Distinct from parenting time, which applies to guardians.", example: "The paternal grandparents want to see the children regularly. They can apply for a contact order if the guardian parent is preventing visits." },
  { term: "Contempt of Court", letter: "C", plain: "Deliberately disobeying a court order. This is a serious offence that can result in fines or jail time.", example: "A court order says children must be returned by 6pm Sunday. The other parent repeatedly returns them at 9pm with no explanation. This may be contempt of court." },
  { term: "Costs", letter: "C", plain: "A court order requiring one party to pay some or all of the other party's legal fees. Costs can be ordered against a party who behaves unreasonably, misses hearings, or wastes court time.", example: "You attended a JCC fully prepared. The other parent showed up with nothing and wasted the session. The judge may award you costs for the wasted time." },
  { term: "Cross-Examination", letter: "C", plain: "Questioning of a witness by the opposing party after the witness has given their main evidence. The goal is to challenge credibility, highlight inconsistencies, or bring out additional facts.", example: "You testify that the children always come home dirty. The other parent's lawyer shows photos of the children clean and happy during visits." },
  { term: "Custody", letter: "C", plain: "The old legal term used before 2020 that described a parent's rights over a child. In Saskatchewan it has been replaced by decision-making responsibility and parenting time. You may still see it in older orders.", example: "An order from 2018 saying sole custody to mother means what today's orders would call sole decision-making responsibility to mother." },
  { term: "Decision-Making Responsibility", letter: "D", plain: "The right and responsibility to make major decisions about a child's life — education, healthcare, religion, and extracurricular activities. This replaced the old term custody in Saskatchewan law in 2020.", example: "An order for joint decision-making responsibility means both parents must agree on which school the child attends." },
  { term: "Default", letter: "D", plain: "When the respondent fails to file an Answer within the required time, usually 30 days. The applicant can then ask the court to proceed without the respondent.", example: "You served the other parent on January 1. They did not file an Answer by January 31. You can now ask the court to note them in default and proceed without them." },
  { term: "Disbursements", letter: "D", plain: "Out-of-pocket expenses incurred during legal proceedings — such as filing fees, process server fees, and photocopy costs. Usually charged in addition to legal fees.", example: "Your lawyer's bill shows $3,000 in legal fees plus $450 in disbursements for filing fees, courier costs, and photocopying." },
  { term: "Disclosure", letter: "D", plain: "The legal obligation to share relevant financial and other information with the other party and the court. Hiding information in family law proceedings is a serious violation.", example: "Financial disclosure means sharing your tax returns, pay stubs, and bank statements so both parties and the court have accurate information." },
  { term: "Discovery", letter: "D", plain: "The legal process of exchanging information and evidence between parties before a hearing. In family law this usually means financial disclosure and sharing of relevant documents.", example: "Before your trial, both parties exchange financial statements, tax returns, pay stubs, and lists of all relevant documents." },
  { term: "Divorce Act", letter: "D", plain: "Federal legislation that governs divorce in Canada. It only applies to legally married couples. It was significantly updated in 2021 to use the language of parenting time and decision-making responsibility.", example: "If you were married, your divorce is governed by the Divorce Act. If you were common-law, your parenting matters are governed by Saskatchewan's Children's Law Act." },
  { term: "Emergency Protection Order", letter: "E", plain: "An urgent court order that can be granted the same day, without notice to the other party, when there is an immediate risk of harm. It can restrict the other party's contact with you or the children.", example: "If the other parent threatens to take the children out of province tonight, you can apply for an Emergency Protection Order at the Court of King's Bench immediately." },
  { term: "Evidence", letter: "E", plain: "Any information presented to the court to prove or disprove a fact — including documents, photographs, text messages, testimony, and expert reports. Evidence must be relevant and admissible.", example: "Text messages, police reports, school records, and your own testimony are all forms of evidence." },
  { term: "Ex Parte", letter: "E", plain: "A Latin term meaning without the other party. An ex parte application is heard by a judge without the other side being present — only used in genuine emergencies.", example: "An ex parte order for emergency custody would be heard with only you present because there is no time to notify the other parent." },
  { term: "Expert Witness", letter: "E", plain: "A person with specialized knowledge who gives opinion evidence in court. Must be qualified by the court as an expert before testifying.", example: "A psychologist who conducted a parenting assessment can testify as an expert about which parent should have primary parenting time." },
  { term: "Family Dispute Resolution", letter: "F", plain: "Any process that helps families resolve disputes without going to court — including mediation, negotiation, and collaborative law. Often required before filing a court application in Saskatchewan.", example: "Family Justice Services in Saskatchewan offers free family dispute resolution. You call them first, and if you cannot agree, they confirm participation for your court file." },
  { term: "Family Justice Services", letter: "F", plain: "A free government service in Saskatchewan that provides mediation, parent education, and family dispute resolution services to help separating parents reach agreements outside of court.", example: "Before filing your court application, you contact Family Justice Services at 1-866-933-5972. A mediator helps you and your ex reach a partial agreement on parenting time." },
  { term: "Filing", letter: "F", plain: "The act of submitting your completed court documents to the court registry. The clerk stamps your documents, assigns a court file number, and keeps the originals.", example: "Filing your Notice of Application at the Court of King's Bench in Regina costs approximately $200. You bring 3 copies and leave one with the court." },
  { term: "Financial Disclosure", letter: "F", plain: "The obligation to share complete and accurate financial information with the other party and the court. Includes tax returns, pay stubs, bank statements, and information about assets and debts.", example: "If you are claiming child support, you must disclose your income. If you are paying child support, the other parent has the right to verify the amount is correct." },
  { term: "Financial Statement", letter: "F", plain: "A court form where you disclose all income, expenses, assets, and debts under oath. Required whenever support or property division is part of the case. Every number must be accurate.", example: "Form 70D in Manitoba or Form 15-26 in Saskatchewan is the financial statement. You attach your tax returns, pay stubs, and bank statements to it." },
  { term: "Parenting After Separation", letter: "F", plain: "A mandatory parenting course in Saskatchewan for separating parents with children. Must be completed before filing. Costs approximately $25 and takes a few hours online.", example: "You register at saskatchewanforkidssake.ca, complete the online course, and receive a certificate. You must attach this certificate to your court application." },
  { term: "Form 15-1", letter: "F", plain: "The Saskatchewan Notice of Application — the main form used to start a court application for parenting, support, or other family matters that do not involve divorce.", example: "If you were never married to the other parent but need a parenting order, Form 15-1 is likely your starting document." },
  { term: "Garnishment", letter: "G", plain: "A legal process that allows the Maintenance Enforcement Office to collect unpaid support directly from a payor's wages or bank account, without going back to court.", example: "The other parent owes 6 months of child support. The MEO contacts their employer and deducts the arrears and ongoing payments directly from their paycheque." },
  { term: "Guardian", letter: "G", plain: "A person who has the legal right and responsibility to care for a child and make decisions about the child's life. In Saskatchewan, both parents are generally guardians unless a court orders otherwise.", example: "As a guardian, you have the right to be informed about your child's education, health, and welfare, regardless of the parenting time schedule." },
  { term: "Guardian ad Litem", letter: "G", plain: "A person appointed by the court to represent a child's interests in legal proceedings — separate from the parents. Sometimes called a litigation guardian.", example: "In a complex custody dispute, the judge appoints a social worker as Guardian ad Litem for the children, who independently reports to the court on what is in the children's best interests." },
  { term: "Hearsay", letter: "H", plain: "A statement made outside of court that is presented in court to prove that what was said is true. Generally not admissible as evidence unless it falls within specific exceptions.", example: "Testifying that your mother told you the other parent was drunk when picking up the children is hearsay. Your mother would need to testify directly." },
  { term: "Income Imputation", letter: "I", plain: "When a court assigns an income to a party that is higher than what they are actually earning, because the court believes they are intentionally underearning to reduce support obligations.", example: "The other parent quit their $80,000/year job to work part-time right before the child support hearing. The court may impute $80,000 income to them anyway." },
  { term: "Injunction", letter: "I", plain: "A court order that requires someone to do something or stop doing something. In family law, an injunction might prevent a parent from removing children from the province.", example: "You have evidence the other parent plans to move the children to another province without consent. You apply for an injunction preventing them from doing so while the case proceeds." },
  { term: "Interim Order", letter: "I", plain: "A temporary court order made while the case is ongoing. It sets the rules until a final order is made — important because cases can take months or years to resolve.", example: "An interim order might say the children live primarily with one parent during the week while the case proceeds, without that being the final decision." },
  { term: "Judgment", letter: "J", plain: "The final decision of a court on the issues in dispute. In family law, a judgment results in a court order that both parties must follow.", example: "After a two-day trial, the judge takes the matter under reserve. Three weeks later, the judgment is issued setting out the final parenting schedule and support amounts." },
  { term: "Judicial Case Conference", letter: "J", plain: "A meeting with a judge in Saskatchewan to discuss the issues in your case, explore settlement, and identify what still needs to be decided. Usually scheduled 4-8 weeks after filing.", example: "At your JCC, the judge might encourage the parties to consider a 7/7 schedule given the children's ages. This gives you a sense of how the judge views the case." },
  { term: "Jurisdiction", letter: "J", plain: "The legal authority of a court to hear a case, and the province or territory whose laws apply to your case. Generally the province where the children live.", example: "If your children live in Saskatchewan, Saskatchewan courts have jurisdiction over parenting matters, even if the other parent lives in Alberta." },
  { term: "Leave of the Court", letter: "L", plain: "Permission from a judge to do something that normally requires court approval. Some applications require leave before they can be heard.", example: "To vary a parenting order within 12 months of the last order, you may need to first get leave of the court to bring the application." },
  { term: "Legal Aid", letter: "L", plain: "Government-funded legal assistance for people who cannot afford a lawyer. In Saskatchewan, Legal Aid Saskatchewan provides services to qualifying individuals.", example: "Legal Aid Saskatchewan can be reached at 1-800-667-3764. Eligibility is based on income. They may be able to help with your custody application." },
  { term: "Litigation", letter: "L", plain: "The process of taking a dispute through the court system. Family litigation is expensive, slow, and emotionally draining — which is why courts encourage settlement whenever possible.", example: "Your case has been in litigation for 18 months, with two JCCs, several motions, and a five-day trial still ahead. Total legal costs so far: $25,000+." },
  { term: "Maintenance Enforcement Office", letter: "M", plain: "A government agency in Saskatchewan that enforces child and spousal support orders. Once a support order is in place, the MEO collects payments from the paying parent and sends them to the receiving parent.", example: "If child support payments stop, you contact the MEO at 1-888-218-2898 and they take enforcement action — including garnishing wages or suspending a driver's licence." },
  { term: "Matrimonial Property", letter: "M", plain: "Assets and debts accumulated during a marriage that are subject to division between spouses upon separation. Saskatchewan's Matrimonial Property Act governs how property is divided for married couples.", example: "The family home, RRSPs, vehicles, and debts acquired during the marriage are matrimonial property and must be divided — usually equally — under Saskatchewan law." },
  { term: "Mediation", letter: "M", plain: "A voluntary, confidential process where a neutral third party helps both parents reach an agreement. Faster and cheaper than court. Free services are available through Family Justice Services in Saskatchewan.", example: "You and the other parent meet with a family mediator three times over two weeks and reach an agreement on a parenting schedule. This agreement can then be filed as a consent order." },
  { term: "Mediation-Arbitration", letter: "M", plain: "A hybrid process where parties first try to mediate, and if they cannot agree, the same neutral becomes an arbitrator and makes a binding decision. Faster than court but binding.", example: "You attend three mediation sessions but cannot agree on the summer parenting schedule. The mediator becomes an arbitrator and issues a binding decision on that issue." },
  { term: "Motion", letter: "M", plain: "A formal request to a court to make a specific order or ruling, usually heard in Chambers. Motions are used to get temporary orders or procedural rulings during a case.", example: "You bring a motion asking the court to order the other parent to disclose their financial documents. The judge hears the motion and orders disclosure within 14 days." },
  { term: "Non-Molestation Order", letter: "N", plain: "A court order preventing one party from contacting, harassing, or molesting the other party or the children. Similar to a restraining order.", example: "Following a domestic violence incident, the court issues a non-molestation order preventing the abusive partner from contacting you, your children, or your parents." },
  { term: "Notice of Application", letter: "N", plain: "The court document that formally starts a family law application in Saskatchewan when divorce is not involved. It sets out who you are, who the other party is, and what orders you are asking for.", example: "Your Notice of Application tells the court you want primary parenting time, $875/month in child support, and joint decision-making responsibility." },
  { term: "Onus of Proof", letter: "O", plain: "The responsibility of proving something in court. In family law, generally the person making an allegation has the onus of proving it on a balance of probabilities.", example: "If you allege the other parent has a substance abuse problem affecting their parenting, you have the onus of providing evidence to support that claim." },
  { term: "Order", letter: "O", plain: "A legally binding decision made by a judge. Once an order is signed, both parties must comply. Violating a court order can result in serious legal consequences.", example: "If a court order says the children are to be picked up at 6pm on Fridays and the other parent consistently ignores it, you can bring the matter back to court." },
  { term: "Parens Patriae", letter: "P", plain: "Latin for parent of the nation. The legal doctrine giving courts the power to make decisions in the best interests of children and other vulnerable people, even without a specific law requiring it.", example: "A judge uses parens patriae jurisdiction to make an unusual order protecting a child in circumstances not specifically covered by the Children's Law Act." },
  { term: "Parenting Assessment", letter: "P", plain: "A formal evaluation by a qualified professional that assesses each parent's ability to care for the children and makes recommendations to the court. Can cost $5,000 to $15,000 or more.", example: "When parents cannot agree and each tells a very different story, a judge may order a parenting assessment. The assessor interviews both parents, the children, and others, then files a report." },
  { term: "Parenting Order", letter: "P", plain: "A court order that sets out the parenting arrangements for children — who they live with, when they spend time with each parent, and who makes major decisions about their lives.", example: "Your parenting order might say children reside primarily with mother, father has parenting time every second weekend and Wednesdays, and both parents have joint decision-making responsibility." },
  { term: "Parenting Plan", letter: "P", plain: "A detailed written agreement between parents about how they will share time with and responsibilities for their children. Can be informal or incorporated into a court order.", example: "A parenting plan might specify who the children are with each day of the week, how holidays are divided, how communication between parents happens, and how major decisions are made." },
  { term: "Parenting Time", letter: "P", plain: "The time a child spends with each parent. Replaced the old term access in Saskatchewan and federal law in 2020-2021. Parenting time does not automatically determine who makes decisions.", example: "An order might give one parent 60% parenting time and the other 40%, with joint decision-making responsibility for major decisions." },
  { term: "Personal Service", letter: "P", plain: "The method of delivering court documents directly to the other person by hand. You cannot serve your own documents — someone else 18+ must do it. Required for starting new court proceedings.", example: "Your adult friend hands the Notice of Application directly to the other parent at their front door. This is personal service." },
  { term: "Petition", letter: "P", plain: "The main court form used to start a divorce or other family law proceeding in Saskatchewan. It sets out what orders you are asking the court to make.", example: "Your Petition tells the court who you are, who the other party is, what happened, what you are asking for, and why." },
  { term: "Pre-Trial Conference", letter: "P", plain: "A meeting with a judge before trial to narrow the issues, discuss settlement, and organize the trial. Usually mandatory before a family law trial in Saskatchewan.", example: "Three weeks before your trial, you attend a Pre-Trial Conference. The judge reviews the issues and signals which matters she expects to be settled versus go to trial." },
  { term: "Primary Residence", letter: "P", plain: "The home where a child lives most of the time. The parent providing primary residence is often but not always the recipient of child support.", example: "The children spend 10 days out of 14 at one parent's home. That parent provides the primary residence." },
  { term: "Queen's Bench", letter: "Q", plain: "The old name for the Court of King's Bench, used when the reigning monarch was a queen. Changed to King's Bench in 2022. You may see Queen's Bench on older court documents and forms.", example: "Your 2019 court order is stamped Court of Queen's Bench for Saskatchewan. This is the same court now called the Court of King's Bench." },
  { term: "Recusal", letter: "R", plain: "When a judge removes themselves from a case because of a conflict of interest or reasonable apprehension of bias.", example: "The judge assigned to your case is a neighbour of the other parent. You apply for the judge to recuse themselves and the case is assigned to a different judge." },
  { term: "Relocation", letter: "R", plain: "Moving to a new location that would significantly affect the other parent's relationship with the children. Saskatchewan law requires advance notice and may require court approval.", example: "If you want to move from Saskatoon to Vancouver with your children, you must give the other parent written notice and they have the right to object." },
  { term: "Respondent", letter: "R", plain: "The person who did not initiate the court case — the one who was served with documents and must respond. The other person is the Applicant or Petitioner.", example: "If the other parent filed the Petition, you are the Respondent. You have 30 days to file your Answer." },
  { term: "Restraining Order", letter: "R", plain: "A court order restricting one party's behaviour — such as preventing them from coming within a certain distance of you or the children.", example: "After a threatening incident, the court issues a restraining order requiring the other parent to stay at least 100 metres from your home, workplace, and children's school." },
  { term: "Section 7 Expenses", letter: "S", plain: "Special or extraordinary expenses for children that are shared by both parents in proportion to their income. Includes childcare, medical costs not covered by insurance, educational expenses, and extracurricular activities.", example: "Your child's braces cost $4,000. If your income is $60,000 and the other parent's is $40,000, you pay 60% and they pay 40%." },
  { term: "Section 21 Disclosure", letter: "S", plain: "The obligation under the Federal Child Support Guidelines to provide your most recent T1 income tax return, Notice of Assessment, and current pay stubs when requested.", example: "The other parent requests section 21 disclosure. You must provide your last 3 years of T1 returns, Notices of Assessment, and 3 months of recent pay stubs within 30 days." },
  { term: "Self-Represented Litigant", letter: "S", plain: "A person who represents themselves in court without a lawyer. Courts make some accommodations for self-represented litigants but still expect you to follow the rules.", example: "You decide to represent yourself at your JCC. The judge may explain procedural steps but will still expect you to have your documents organized and your position clearly stated." },
  { term: "Separation Agreement", letter: "S", plain: "A written contract between separating partners that sets out how they will handle parenting, support, and property division. Not the same as a court order, but can be filed with the court to become enforceable.", example: "You and your ex work with a mediator to create a separation agreement covering parenting schedules, child support, and division of assets. Both sign it and it can be filed as a consent order." },
  { term: "Service", letter: "S", plain: "The legal process of officially delivering court documents to the other party. Different methods are allowed in different situations. Personal service is required to start a new case.", example: "After you file your Petition, you must serve the other parent. A process server can be hired to do this for approximately $100 to $200." },
  { term: "Shared Parenting", letter: "S", plain: "An arrangement where the children spend at least 40% of their time with each parent. This can affect the child support calculation — both parents' incomes are considered.", example: "A 50/50 arrangement where children alternate weeks between homes is shared parenting. The parent with the higher income typically pays the difference between the two table amounts." },
  { term: "Spousal Support", letter: "S", plain: "Financial support paid from one spouse to the other after separation. The amount and duration depend on factors like income difference, length of relationship, and roles during the marriage.", example: "If one spouse stayed home with children for 10 years while the other built a career, spousal support might be ordered to help the stay-at-home parent re-establish financially." },
  { term: "Stay of Proceedings", letter: "S", plain: "A court order halting or pausing a case or part of it. Can be temporary or permanent.", example: "One party files an appeal of an interim order. The court grants a stay of proceedings while the appeal is heard, meaning the old arrangement continues temporarily." },
  { term: "Subpoena", letter: "S", plain: "A court document ordering a person to appear in court as a witness or to produce documents. Ignoring a subpoena can result in arrest.", example: "The other parent's employer has records showing irregular pay. You subpoena the payroll records to confirm the actual income for child support purposes." },
  { term: "Summary Advice Counsel", letter: "S", plain: "Free legal advice provided by Legal Aid Saskatchewan lawyers at most courthouses. Available to unrepresented parties to help them understand the process and their documents before a hearing.", example: "On the day of your JCC, you arrive early and meet with Summary Advice Counsel. They review your JCC brief for 20 minutes and suggest points you should emphasize." },
  { term: "Trial", letter: "T", plain: "A formal court proceeding where both parties present evidence and witnesses, and a judge makes a final decision. Trials are rare in family law — most cases settle beforehand.", example: "If the JCC and all other attempts at settlement fail, a trial date is set. You present your evidence, the other party presents theirs, and the judge decides." },
  { term: "Undertaking", letter: "U", plain: "A formal promise made to the court, usually in writing. An undertaking is legally binding and violating it has serious consequences.", example: "You give an undertaking not to remove the children from Saskatchewan pending the outcome of the case. If you violate this undertaking, you can be held in contempt of court." },
  { term: "Undue Hardship", letter: "U", plain: "A legal claim that the standard child support amount causes exceptional financial hardship. Requires showing specific circumstances, such as unusually high access costs or legal obligations to other children.", example: "You pay $1,200/month to fly your children from Saskatchewan to BC for your parenting time. You claim undue hardship and ask the court to reduce the guideline amount to account for these costs." },
  { term: "Variation", letter: "V", plain: "The process of changing an existing court order. Requires showing a significant change in circumstances since the original order was made.", example: "Your original order was based on an income of $50,000. You were laid off and now earn $30,000. You apply for a variation order to reduce your child support payments." },
  { term: "Variation Order", letter: "V", plain: "A new court order that changes or replaces a previous order, made when there has been a significant change in circumstances since the original order was issued.", example: "Your income dropped by 40% after losing your job. This is a significant change in circumstances that justifies applying to vary your child support payments." },
  { term: "Viva Voce Evidence", letter: "V", plain: "Live oral testimony given in court by a witness — as opposed to evidence given in writing through an affidavit. Latin for by living voice.", example: "At trial, you give viva voce evidence — you testify in person and are then cross-examined by the other party or their lawyer." },
  { term: "Without Notice Application", letter: "W", plain: "An urgent application heard by a judge without the other party being present or notified. Only granted in genuine emergencies where delay would cause serious harm.", example: "If you have evidence the other parent plans to take the children out of Canada tonight, you can file a without notice application asking the court to prevent it immediately." },
  { term: "Without Prejudice", letter: "W", plain: "Communications or offers made without prejudice cannot be used as evidence in court. Used in settlement negotiations to allow frank discussion without risk.", example: "Your lawyer sends a without prejudice letter offering to settle parenting time. If the other side refuses and you go to trial, this settlement offer cannot be shown to the judge." },
  { term: "Witness", letter: "W", plain: "A person who gives evidence in court, either by sworn testimony or by affidavit. Witnesses must tell the truth — lying in court is perjury, a criminal offence.", example: "Your child's teacher witnessed concerning behaviour by the other parent at school pickup. You can call the teacher as a witness to testify about what they saw." },
];

const LETTERS = [...new Set(TERMS.map(t => t.letter))].sort();

export default function GlossaryPage() {
  const [search, setSearch] = useState('');
  const [activeLetter, setActiveLetter] = useState(null);
  const [expandedTerm, setExpandedTerm] = useState(null);

  const filtered = TERMS.filter(t => {
    const matchesSearch = !search || t.term.toLowerCase().includes(search.toLowerCase()) || t.plain.toLowerCase().includes(search.toLowerCase());
    const matchesLetter = !activeLetter || t.letter === activeLetter;
    return matchesSearch && matchesLetter;
  });

  const grouped = {};
  filtered.forEach(t => {
    if (!grouped[t.letter]) grouped[t.letter] = [];
    grouped[t.letter].push(t);
  });

  return (
    <div className="min-h-screen bg-gray-50">
      <Header />
      <PageTitle title="Legal Glossary" subtitle="Plain language definitions for family law terms" icon="📖" />

      <main className="max-w-3xl mx-auto px-4 py-6 space-y-5">
        <div className="relative">
          <span className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400 text-sm">🔍</span>
          <input
            type="text"
            value={search}
            onChange={e => { setSearch(e.target.value); setActiveLetter(null); }}
            placeholder="Search a term or keyword..."
            className="w-full pl-10 pr-4 py-3 bg-white border border-gray-200 rounded-xl text-sm text-gray-900 placeholder-gray-400 focus:outline-none focus:border-red-400"
          />
          {search && (
            <button onClick={() => setSearch('')} className="absolute right-4 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600 text-sm">✕</button>
          )}
        </div>

        {!search && (
          <div className="flex flex-wrap gap-1.5">
            <button onClick={() => setActiveLetter(null)} className={`px-2.5 py-1 rounded-lg text-xs font-semibold transition-colors ${!activeLetter ? 'bg-red-600 text-white' : 'bg-white border border-gray-200 text-gray-600 hover:border-red-300'}`}>All</button>
            {LETTERS.map(l => (
              <button key={l} onClick={() => setActiveLetter(activeLetter === l ? null : l)} className={`px-2.5 py-1 rounded-lg text-xs font-semibold transition-colors ${activeLetter === l ? 'bg-red-600 text-white' : 'bg-white border border-gray-200 text-gray-600 hover:border-red-300'}`}>{l}</button>
            ))}
          </div>
        )}

        <div className="bg-amber-50 border border-amber-200 rounded-xl p-3">
          <p className="text-xs text-amber-800"><strong>Educational only.</strong> These definitions are plain-language explanations to help you understand legal terms. They are not legal advice. Consult a lawyer for advice specific to your situation.</p>
        </div>

        {filtered.length === 0 ? (
          <div className="bg-white border border-gray-200 rounded-xl p-8 text-center">
            <p className="text-gray-500 text-sm">No terms found for "{search}"</p>
            <button onClick={() => setSearch('')} className="text-red-600 text-sm mt-2 hover:underline">Clear search</button>
          </div>
        ) : (
          Object.entries(grouped).map(([letter, terms]) => (
            <div key={letter}>
              <div className="flex items-center gap-3 mb-2">
                <div className="w-8 h-8 bg-red-600 rounded-lg flex items-center justify-center text-white font-bold text-sm flex-shrink-0">{letter}</div>
                <div className="h-px flex-1 bg-gray-200" />
              </div>
              <div className="space-y-2">
                {terms.map(term => {
                  const isOpen = expandedTerm === term.term;
                  return (
                    <div key={term.term} className="bg-white border border-gray-200 rounded-xl overflow-hidden">
                      <button onClick={() => setExpandedTerm(isOpen ? null : term.term)} className="w-full flex items-center justify-between p-4 text-left hover:bg-gray-50 transition-colors">
                        <span className="font-semibold text-gray-900 text-sm">{term.term}</span>
                        <span className="text-gray-400 text-sm ml-3 flex-shrink-0">{isOpen ? '▲' : '▼'}</span>
                      </button>
                      {isOpen && (
                        <div className="px-4 pb-4 pt-0 border-t border-gray-100 space-y-3">
                          <p className="text-sm text-gray-700 leading-relaxed pt-3">{term.plain}</p>
                          {term.example && (
                            <div className="bg-blue-50 border border-blue-100 rounded-lg p-3">
                              <p className="text-xs font-semibold text-blue-800 mb-1">📌 Example</p>
                              <p className="text-xs text-blue-800 leading-relaxed">{term.example}</p>
                            </div>
                          )}
                          <Link href={`/ai?q=${encodeURIComponent('Explain ' + term.term + ' in the context of my Saskatchewan family law case')}`} className="inline-flex items-center gap-1.5 text-xs text-red-600 font-medium hover:underline">
                            💬 Ask AI about this →
                          </Link>
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>
            </div>
          ))
        )}

        <Footer />
      </main>
    </div>
  );
}
